---
AWSTemplateFormatVersion: 2010-09-09

Description: Notejam ELB

Parameters:
  VpcStackName:
    Description: VPC Cloudformation stack name
    Type: String

Resources:
  ElbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Elastic Load Balancer"
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-vpc"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "elb-sg-${AWS::StackName}"

  ElbToNodesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for EC2 instances"
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-vpc"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref ElbSecurityGroup
          IpProtocol: TCP
          FromPort: 5000
          ToPort: 5000
      Tags:
        - Key: Name
          Value: !Sub "ec2-sg-${AWS::StackName}"

  Elb:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "elb-${AWS::StackName}"
      SecurityGroups:
        - !Ref ElbSecurityGroup
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue: !Sub "${VpcStackName}-public-subnet1"
        - Fn::ImportValue: !Sub "${VpcStackName}-public-subnet2"
        - Fn::ImportValue: !Sub "${VpcStackName}-public-subnet3"
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '5000'
          Protocol: HTTP
      HealthCheck:
        Target: "HTTP:5000/"
        HealthyThreshold: '2'
        UnhealthyThreshold: '2'
        Interval: '10'
        Timeout: '5'
      CrossZone: true
      ConnectionSettings:
        IdleTimeout: 60
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300

Outputs:
  Elb:
    Description: The ID Elastic Load Balancer.
    Value: !Ref Elb